/**
 * SixShopErrorCode
 */

export enum SixShopErrorCode {
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',
  QUERY_ERROR = 'QUERY_ERROR',
  UUID_ERROR = 'UUID_ERROR',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  NOT_MATCH_USER = 'NOT_MATCH_USER',
  PASSWORD_INCORRECT = 'PASSWORD_INCORRECT',
  DUPLICATE_EMAIL = 'DUPLICATE_EMAIL',
  NOT_DUPLICATE_PASSWORD = 'NOT_DUPLICATE_PASSWORD',
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  NOT_ALLOWED_USER = 'NOT_ALLOWED_USER',
  APPROVE_USER_NOT_FOUND = 'APPROVE_USER_NOT_FOUND',
  NOT_FOUND_CUSTOM_TYPE = 'NOT_FOUND_CUSTOM_TYPE',
  DUPLICATE_NAME = 'DUPLICATE_NAME',
  IT_EXISTS_BUT_HAS_NO_CUSTOM_VALUE = 'IT_EXISTS_BUT_HAS_NO_CUSTOM_VALUE',
  NOT_CREATE_SHOP = 'NOT_CREATE_SHOP',
  NOT_FOUND_SHOP = 'NOT_FOUND_SHOP',
  NOT_FOUND_MY_SHOP = 'NOT_FOUND_MY_SHOP',
}
